import { GeistMono } from 'geist/font/mono'
import "./globals.css";
import Provider from './provider';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistMono.className} dark`} suppressHydrationWarning>
      <body>
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}
